// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using microprojeto_aspnet_PersonalBudget.Data;

#nullable disable

namespace microprojeto_aspnet_PersonalBudget.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("microprojeto_aspnet_PersonalBudget.Models.Etiqueta", b =>
                {
                    b.Property<string>("EtiquetaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EtiquetaId");

                    b.ToTable("Etiquetas");

                    b.HasData(
                        new
                        {
                            EtiquetaId = "alimentacao",
                            Nome = "Alimentação"
                        },
                        new
                        {
                            EtiquetaId = "transporte",
                            Nome = "Transporte"
                        },
                        new
                        {
                            EtiquetaId = "saude",
                            Nome = "Saúde"
                        },
                        new
                        {
                            EtiquetaId = "moradia",
                            Nome = "Moradia"
                        },
                        new
                        {
                            EtiquetaId = "lazer",
                            Nome = "Lazer"
                        });
                });

            modelBuilder.Entity("microprojeto_aspnet_PersonalBudget.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("EtiquetaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("StatusId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("microprojeto_aspnet_PersonalBudget.Models.Status", b =>
                {
                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = "pago",
                            Nome = "Pago"
                        },
                        new
                        {
                            StatusId = "nao-pago",
                            Nome = "Não Pago"
                        });
                });

            modelBuilder.Entity("microprojeto_aspnet_PersonalBudget.Models.Registro", b =>
                {
                    b.HasOne("microprojeto_aspnet_PersonalBudget.Models.Etiqueta", "Etiqueta")
                        .WithMany()
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("microprojeto_aspnet_PersonalBudget.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
